import { StoreProvider } from '@/redux/provider'
import { ThemeProvider } from '@/components/ThemeProvider/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import styles from '@/app/page.module.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: 'manifest.json',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <StoreProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <div className={styles.container}>
              <Header />
              {children}
            </div>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
